In [1]:

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('KeyWordOccurrences2.csv',header=None)
df=df.drop([0],axis=1)   #删除0、1列（都是序号）
df=df.drop([1],axis=0)
df.columns=range(df.shape[1])     
display(df)

0                                                  1   \
0                  name                                              genre   
2        3rd Revelation                                        Black Metal   
3       5 Days Bleeding                    Melodic Death/Power/Black Metal   
4       5 Days Bleeding                    Melodic Death/Power/Black Metal   
5       5 Days Bleeding                    Melodic Death/Power/Black Metal   
...                 ...                                                ...   
238848               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   
238849               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   
238850               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   
238851               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   
238852               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   

        2   3   4   5   6   7   8   9   ...  15  16  17  18  19  20  21  22  \
0        1   2   3   4   5   6   7   8  ...  14  15  16  17  18  19  20  21   
2        2   1   1   1   2   1   0   2  ...   1   0   2   3   3   0   1   3   
3        0   0   0   2   0   0   2   4  ...   0   1   1   2   0   0   2   5   
4        0   0   0   0   0   0   1   1  ...   1   0   0   0   2   1   3   3   
5        1   0   0   0   1   0   0   1  ...   0   1   0   2   0   2   1   2   
...     ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..   
238848   1   0   0   1   1   0   1   2  ...   0   0   2   0   0   0   2   0   
238849   0   0   0   0   0   0   1   1  ...   0   0   1   2   0   0   0   0   
238850   0   2   0   1   0   2   2   4  ...   0   0   4   1   1   1   2   0   
238851   0   0   0   0   0   0   1   2  ...   0   0   0   0   0   0   2   0   
238852   0   0   0   0   0   0   1   2  ...   1   0   1   0   2   0   3   2   

        23  24  
0       22  23  
2        0   1  
3        2   2  
4        1   1  
5        1   0  
...     ..  ..  
238848   0   0  
238849   0   1  
238850   0   1  
238851   1   0  
238852   0   0  

[238852 rows x 25 columns]

In [2]:
# train和test的分界位置：前2/3用作训练，后1/3用作测试
M=np.int32(df.shape[0]*2/3)
IVarCnt=df.shape[1]-2          #自变量个数: 注意最后两列是歌曲名称、歌曲类型
print(M,'/',df.shape[0],'\n')

159234 / 238852 



In [3]:
# 自变量
ColSet=range(2,IVarCnt+2)                 #自变量在数据集中的位置（列）
x_train=df.iloc[2:M,ColSet].values   
x_test= df.iloc[M:, ColSet].values   

print('\nx_train',x_train.shape)
print(x_train)
print('\nx_test',x_test.shape)
print(x_test)


x_train (159232, 23)
[[0 0 0 ... 5 2 2]
 [0 0 0 ... 3 1 1]
 [1 0 0 ... 2 1 0]
 ...
 [0 0 0 ... 1 2 1]
 [0 0 0 ... 2 1 3]
 [2 0 0 ... 2 1 0]]

x_test (79618, 23)
[[0 0 0 ... 1 0 1]
 [0 0 0 ... 3 2 0]
 [0 1 1 ... 3 1 0]
 ...
 [0 2 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 2 0 0]]


In [4]:
# 为因变量准备原始数据
Y=df.iloc[:,1].values     #第1列，即：歌曲类型
Y_train=Y[2:M]
Y_test= Y[M:]

print('\nY_train',Y_train.shape)
print(Y_train)
print('\nY_test',Y_test.shape)
print(Y_test)

print('\nY',Y.shape)
print(Y)


Y_train (159232,)
['Melodic Death/Power/Black Metal' 'Melodic Death/Power/Black Metal'
 'Melodic Death/Power/Black Metal' ... 'Death/Thrash Metal'
 'Death/Thrash Metal' 'Death/Thrash Metal']

Y_test (79618,)
['Death/Thrash Metal' 'Death/Thrash Metal' 'Death/Thrash Metal' ...
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)'
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)'
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)']

Y (238852,)
['genre' 'Black Metal' 'Melodic Death/Power/Black Metal' ...
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)'
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)'
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)']


In [5]:
import pandas as pd
BlackType=pd.read_csv('Black Metal Types.csv').reset_index()
BlackType=BlackType.drop(['index'],axis=1)
BlackType.columns=['type','numbers']
display(BlackType)

T00=BlackType[BlackType['numbers']<=500]['type'].values
T00=T00.tolist()

T01=['Pagan Black Metal','Industrial Black Metal','Epic Black Metal']
T02=['Blackened Thrash Metal','Blackened Death Metal','Blackened Metal']
T03=['Progressive Black Metal','Experimental Black Metal','Avant-garde Black Metal']
T04=['Post-Black Metal']
T05=['Depressive Black Metal']
T06=['Raw Black Metal']
T07=['Atmospheric Black Metal']
T08=['Symphonic Black Metal']
T09=['Melodic Black Metal']
T10=['Black Metal']
T11=['Black']

SongType=[T00,T01,T02,T03,T04,T05,T06,T07,T08,T09,T10,T11]

type  numbers
0                                         Black   177416
1                                 Melodic Black     9132
2                               Symphonic Black     6911
3                                     Blackened     6493
4                             Atmospheric Black     4715
..                                          ...      ...
141                  Industrial Blackened Death        1
142                   Blackened Technical Death        1
143  Blackened Heavy Metal with Folk influences        1
144                 Technical Progressive Black        1
145                          Thrash  Epic Black        0

[146 rows x 2 columns]

In [6]:
def IsBandType(song,typeidx):
    s=song
    Arr=[]
    while True:
        p=s.find('/')
        if(p>0):
            Arr.append(s[0:p])
            s=s[p+1:]
        else:
            Arr.append(s)
            break
    b=False
    for s in Arr:
        for type in SongType[typeidx]:
            if s==type:
                b=True
                break
        if b:
            break       
    return b



 
# 回归模型预测值   


def activation(X,w,b):
    return (np.dot(X,w)+b)      # dot(X,w): 两个向量的点乘

def loss(X,y, w, b):
    dif=y- activation(X, w,b)
    return np.sum(dif**2/(2*len(y)),keepdims=True)

def accuracy(X, y, w, b):
    pre = predict(X, w, b)
    return np.sum(np.where(pre==y,1,0))/len(y)    
 
def predict(X, w, b):
    result = np.int32(activation(X,w,b)+0.5)    #                      
    return result

def update(X, y, w, b, eta):  #将w和b的值分别稍微调大，根据损失函数的变化，调整w和b
    h =1e-4
    loss_origin = loss(X, y, w, b)                       # 损失函数
    delta_w=np.zeros_like(w) 
    delta_b=np.zeros_like(b) 
    
    for i in range(len(w)):
        tmp=w[i]
        w[i]+=h                                          # 将参数w中的一个值稍微调大一点 
        loss_after=loss(X,y,w,b)                         # 损失函数
        delta_w[i] =eta*(loss_after - loss_origin)/h     # 损失函数的增量
        w[i]=tmp 
        
    tmp=b 
    b += h                                                # 将参数b中的一个值稍微调大一点 
    loss_after = loss(X, y, w, b)
    delta_b=eta*(loss_after-loss_origin)/h
    b=tmp
        
    w-=delta_w    # 更新参数值 
    b-=delta_b 
    
    #print('Delta:',delta_w,delta_b)
    return w,b

In [8]:
for m in range(len(SongType)):
    print('\n-------------------',m,SongType[m][0],'--------------------\n')
    
    # 将Y中的歌曲类型转化为数值0-1: 根据是否为第m个歌曲类型，
    # 然后把转化后的y作为因变量
    y=np.zeros(df.shape[0]) # 用于转化为数值0-1，代表是否是第m类歌曲 

    for i in range(len(Y)):
        if IsBandType(Y[i],m):
            y[i]=1     # 转化为数值0-1
        else:
            y[i]=0
    print('y=',y)
    print('count=',np.sum(y)) 

    # 确定训练用的因变量、测试用的因变量
    y_train=y[2:M]                          
    y_test= y[M:]
    
    
    print('x_train:',x_train)
    print('length:',len(x_train))
    
    print('x_test:',x_test)
    print('length:',len(x_test))
    
    print('y_train:',y_train)
    print('length:',len(y_train))
    
    print('y_test:',y_test)
    print('length:',len(y_test))
    
    # 初试化w和b，都取0.1
    weights=np.ones(IVarCnt)/10 
    bias=np.ones(1)/10
    
    ##建立模型：
    
    
    for k in range(20): # 让模型进行多次学习 
        weights, bias = update(x_train ,y_train, weights, bias,eta=0.01)
    
    pre=predict(x_test, weights, bias)
    acc=accuracy(x_test, y_test, weights, bias)
    
    ####r_sq = model.score(x_test, y_test)
    #weights=model.coef_    
    #bias=model.intercept_
    
    
    #predict(x_train, weights, bias)
    #print('my prediction:',predict(x_train, weights, bias))
    #print('my accuracy:',accuracy(x_train, y_train, weights, bias))
    
    
    
     # 打印模型准确度
    print('Accuracy=%.2f%%' % (100*acc))
        
        
    # 打印模型的系数  
    print('w=',weights)
    print('b=',bias)
    
    pre=predict(x_test,weights,bias)                # 预测值（歌曲是否第m类）
    if m==0:      
        pre=pre.reshape(-1,1)
        PreArr=pre                                  # 保存预测值（歌曲是否第m类）
        y_test=y_test.reshape(-1,1)
        ActArr=y_test                               # 保存实际值（歌曲是否第m类） 
    else:    
        PreArr=np.insert(PreArr,m,pre,axis=1)       # 保存预测值（歌曲是否第m类）  
        ActArr=np.insert(ActArr,m,y_test,axis=1)    # 保存实际值（歌曲是否第m类）




------------------- 0 Ambient Black --------------------

y= [0. 0. 0. ... 0. 0. 0.]
count= 866.0
x_train: [[0 0 0 ... 5 2 2]
 [0 0 0 ... 3 1 1]
 [1 0 0 ... 2 1 0]
 ...
 [0 0 0 ... 1 2 1]
 [0 0 0 ... 2 1 3]
 [2 0 0 ... 2 1 0]]
length: 159232
x_test: [[0 0 0 ... 1 0 1]
 [0 0 0 ... 3 2 0]
 [0 1 1 ... 3 1 0]
 ...
 [0 2 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 2 0 0]]
length: 79618
y_train: [0. 0. 0. ... 0. 0. 0.]
length: 159232
y_test: [0. 0. 0. ... 0. 0. 0.]
length: 79618
Accuracy=99.18%
w= [ 0.02444781  0.05306773  0.06285719  0.02681986  0.02444781  0.05306773
  0.03724108 -0.04184502  0.03668028  0.00704052  0.02444781  0.06148953
 -0.05517891  0.04178446  0.01088581  0.00269291 -0.01203556  0.00695457
  0.04472497 -0.01096895 -0.06334675  0.03619336  0.01926993]
b= [0.02328748]

------------------- 1 Pagan Black Metal --------------------

y= [0. 0. 0. ... 0. 0. 0.]
count= 951.0
x_train: [[0 0 0 ... 5 2 2]
 [0 0 0 ... 3 1 1]
 [1 0 0 ... 2 1 0]
 ...
 [0 0 0 ... 1 2 1]
 [0 0 0 ... 

Accuracy=74.09%
w= [ 0.02961889  0.0558543   0.06788425  0.03428142  0.02961889  0.0558543
  0.04271364 -0.02757376  0.04271535  0.01672668  0.02961889  0.0660304
 -0.03774402  0.05076262  0.02158953  0.0143992  -0.00260775  0.01333691
  0.04834118 -0.00482755 -0.0487582   0.04237799  0.02740336]
b= [0.03853095]

------------------- 11 Black --------------------

y= [0. 0. 0. ... 0. 0. 0.]
count= 19918.0
x_train: [[0 0 0 ... 5 2 2]
 [0 0 0 ... 3 1 1]
 [1 0 0 ... 2 1 0]
 ...
 [0 0 0 ... 1 2 1]
 [0 0 0 ... 2 1 3]
 [2 0 0 ... 2 1 0]]
length: 159232
x_test: [[0 0 0 ... 1 0 1]
 [0 0 0 ... 3 2 0]
 [0 1 1 ... 3 1 0]
 ...
 [0 2 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 2 0 0]]
length: 79618
y_train: [0. 0. 0. ... 0. 0. 0.]
length: 159232
y_test: [0. 0. 0. ... 0. 0. 0.]
length: 79618
Accuracy=91.22%
w= [ 0.02664577  0.05413391  0.06442465  0.02887087  0.02664577  0.05413391
  0.03948545 -0.03667471  0.03902092  0.01045333  0.02664577  0.06303208
 -0.04998871  0.04489178  0.01481395  0.0063766