In [1]:

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('KeyWordOccurrences2.csv',header=None)
df=df.drop([0],axis=1)   #删除0、1列（都是序号）
df=df.drop([1],axis=0)
df.columns=range(df.shape[1])     
display(df)

0                                                  1   \
0                  name                                              genre   
2        3rd Revelation                                        Black Metal   
3       5 Days Bleeding                    Melodic Death/Power/Black Metal   
4       5 Days Bleeding                    Melodic Death/Power/Black Metal   
5       5 Days Bleeding                    Melodic Death/Power/Black Metal   
...                 ...                                                ...   
238848               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   
238849               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   
238850               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   
238851               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   
238852               暴君  Melodic Black/Folk Metal (early); Melodic Deat...   

        2   3   4   5   6   7   8   9   ...  15  16  17  18  19  20  21  22  \
0        1   2   3   4   5   6   7   8  ...  14  15  16  17  18  19  20  21   
2        2   1   1   1   2   1   0   2  ...   1   0   2   3   3   0   1   3   
3        0   0   0   2   0   0   2   4  ...   0   1   1   2   0   0   2   5   
4        0   0   0   0   0   0   1   1  ...   1   0   0   0   2   1   3   3   
5        1   0   0   0   1   0   0   1  ...   0   1   0   2   0   2   1   2   
...     ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..   
238848   1   0   0   1   1   0   1   2  ...   0   0   2   0   0   0   2   0   
238849   0   0   0   0   0   0   1   1  ...   0   0   1   2   0   0   0   0   
238850   0   2   0   1   0   2   2   4  ...   0   0   4   1   1   1   2   0   
238851   0   0   0   0   0   0   1   2  ...   0   0   0   0   0   0   2   0   
238852   0   0   0   0   0   0   1   2  ...   1   0   1   0   2   0   3   2   

        23  24  
0       22  23  
2        0   1  
3        2   2  
4        1   1  
5        1   0  
...     ..  ..  
238848   0   0  
238849   0   1  
238850   0   1  
238851   1   0  
238852   0   0  

[238852 rows x 25 columns]

In [2]:
# train和test的分界位置：前2/3用作训练，后1/3用作测试
M=np.int32(df.shape[0]*2/3)
IVarCnt=df.shape[1]-2          #自变量个数: 注意最后两列是歌曲名称、歌曲类型
print(M,'/',df.shape[0],'\n')

159234 / 238852 



In [3]:
# 自变量
ColSet=range(2,IVarCnt+2)                 #自变量在数据集中的位置（列）
x_train=df.iloc[2:M,ColSet].values   
x_test= df.iloc[M:, ColSet].values   

print('\nx_train',x_train.shape)
print(x_train)
print('\nx_test',x_test.shape)
print(x_test)


x_train (159232, 23)
[[0 0 0 ... 5 2 2]
 [0 0 0 ... 3 1 1]
 [1 0 0 ... 2 1 0]
 ...
 [0 0 0 ... 1 2 1]
 [0 0 0 ... 2 1 3]
 [2 0 0 ... 2 1 0]]

x_test (79618, 23)
[[0 0 0 ... 1 0 1]
 [0 0 0 ... 3 2 0]
 [0 1 1 ... 3 1 0]
 ...
 [0 2 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 2 0 0]]


In [4]:
# 为因变量准备原始数据
Y=df.iloc[:,1].values     
Y_train=Y[2:M]
Y_test= Y[M:]

print('\nY_train',Y_train.shape)
print(Y_train)
print('\nY_test',Y_test.shape)
print(Y_test)

print('\nY',Y.shape)
print(Y)


Y_train (159232,)
['Melodic Death/Power/Black Metal' 'Melodic Death/Power/Black Metal'
 'Melodic Death/Power/Black Metal' ... 'Death/Thrash Metal'
 'Death/Thrash Metal' 'Death/Thrash Metal']

Y_test (79618,)
['Death/Thrash Metal' 'Death/Thrash Metal' 'Death/Thrash Metal' ...
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)'
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)'
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)']

Y (238852,)
['genre' 'Black Metal' 'Melodic Death/Power/Black Metal' ...
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)'
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)'
 'Melodic Black/Folk Metal (early); Melodic Death/Folk Metal (later)']


In [5]:
import pandas as pd
BlackType=pd.read_csv('Black Metal Types.csv').reset_index()
BlackType=BlackType.drop(['index'],axis=1)
BlackType.columns=['type','numbers']
display(BlackType)

T00=BlackType[BlackType['numbers']<=500]['type'].values
T00=T00.tolist()

T01=['Pagan Black Metal','Industrial Black Metal','Epic Black Metal']
T02=['Blackened Thrash Metal','Blackened Death Metal','Blackened Metal']
T03=['Progressive Black Metal','Experimental Black Metal','Avant-garde Black Metal']
T04=['Post-Black Metal']
T05=['Depressive Black Metal']
T06=['Raw Black Metal']
T07=['Atmospheric Black Metal']
T08=['Symphonic Black Metal']
T09=['Melodic Black Metal']
T10=['Black Metal']
T11=['Black']

SongType=[T00,T01,T02,T03,T04,T05,T06,T07,T08,T09,T10,T11]

type  numbers
0                                         Black   177416
1                                 Melodic Black     9132
2                               Symphonic Black     6911
3                                     Blackened     6493
4                             Atmospheric Black     4715
..                                          ...      ...
141                  Industrial Blackened Death        1
142                   Blackened Technical Death        1
143  Blackened Heavy Metal with Folk influences        1
144                 Technical Progressive Black        1
145                          Thrash  Epic Black        0

[146 rows x 2 columns]

In [6]:
def IsBandType(song,typeidx):
    s=song
    Arr=[]
    while True:
        p=s.find('/')
        if(p>0):
            Arr.append(s[0:p])
            s=s[p+1:]
        else:
            Arr.append(s)
            break
    b=False
    for s in Arr:
        for type in SongType[typeidx]:
            if s==type:
                b=True
                break
        if b:
            break       
    return b


# 回归模型精度
def accuracy(X, y, w, b):
    result = predict(X, w, b)
    return np.sum(np.where(result==y,1,0))/len(y)    
 
# 回归模型预测值   

def predict(X, w, b):
    v=np.dot(X,w)+b
    result =np.where(v>=0.5, 1, 0)                      
    return result

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB

for m in range(len(SongType)):
    print('\n-------------------',m,SongType[m][0],'--------------------\n')
    
    # 将Y中的歌曲类型转化为数值0-1: 根据是否为第m个歌曲类型，
    # 然后把转化后的y作为因变量
    y=np.zeros(df.shape[0]) # 用于转化为数值0-1，代表是否是第m类歌曲 

    for i in range(len(Y)):
        if IsBandType(Y[i],m):
            y[i]=1     # 转化为数值0-1
        else:
            y[i]=0
    print('y=',y)
    print('count=',np.sum(y)) 

    # 确定训练用的因变量、测试用的因变量
    y_train=y[2:M]                          
    y_test= y[M:]
    
    print('y_train:',y_train)
    print('length:',len(y_train))
    print('\n')
    print('y_test:',y_test)
    print('length:',len(y_test))
    
    
    ##建立模型：    
    
    gnb=GaussianNB()
    gnb.fit(x_train,y_train)
    acc=gnb.score(x_test,y_test)
    
    print('Accuracy:={}%'.format(acc*100))

    pre=gnb.predict(x_test)
    
                                                     # 预测值（歌曲是否第m类）
    if m==0:      
        pre=pre.reshape(-1,1)
        PreArr=pre                                  # 保存预测值（歌曲是否第m类）
        y_test=y_test.reshape(-1,1)
        ActArr=y_test                               # 保存实际值（歌曲是否第m类） 
    else:    
        PreArr=np.insert(PreArr,m,pre,axis=1)       # 保存预测值（歌曲是否第m类）  
        ActArr=np.insert(ActArr,m,y_test,axis=1)    # 保存实际值（歌曲是否第m类）




------------------- 0 Ambient Black --------------------

y= [0. 0. 0. ... 0. 0. 0.]
count= 866.0
y_train: [0. 0. 0. ... 0. 0. 0.]
length: 159232


y_test: [0. 0. 0. ... 0. 0. 0.]
length: 79618
Accuracy:=99.49257705543972%

------------------- 1 Pagan Black Metal --------------------

y= [0. 0. 0. ... 0. 0. 0.]
count= 951.0
y_train: [0. 0. 0. ... 0. 0. 0.]
length: 159232


y_test: [0. 0. 0. ... 0. 0. 0.]
length: 79618
Accuracy:=99.52648898490291%

------------------- 2 Blackened Thrash Metal --------------------

y= [0. 0. 0. ... 0. 0. 0.]
count= 2074.0
y_train: [0. 0. 0. ... 0. 0. 0.]
length: 159232


y_test: [0. 0. 0. ... 0. 0. 0.]
length: 79618
Accuracy:=99.32552940289884%

------------------- 3 Progressive Black Metal --------------------

y= [0. 0. 0. ... 0. 0. 0.]
count= 714.0
y_train: [0. 0. 0. ... 0. 0. 0.]
length: 159232


y_test: [0. 0. 0. ... 0. 0. 0.]
length: 79618
Accuracy:=99.66590469491824%

------------------- 4 Post-Black Metal --------------------

y= [0. 0. 0. ... 0